import time
import sys
import os

a = 0 # regular break
b = 1 # longer break
c = 0.5 # very short break
d= 0.005

def accept_func():
    print()
    accept = input("Will you go and investigate the object? (y/n) ")
    if accept == "y":
        time.sleep(c)
        mission_accepted()
    elif accept == "n":
        time.sleep(c)
        print()
        print("Failing to accept a task can be harmful to your career.")
        print("We strongly suggest you accept this assignment.")
        accept_func()
    else:
        time.sleep(c)
        print()
        print("Sorry. Input not recognised.")
        accept_func()

def mission_accepted():
    print()
    print("I lie in bed for a few moments.")
    time.sleep(a)
    print("I think I know where moon WR34 is.")
    time.sleep(a)
    print("Not far from where I'm currently staying.")
    time.sleep(a)
    print("It shouldn't take long for me to get there.")
    time.sleep(b)
    print("I check the location on my tablet.")
    time.sleep(a)
    print("It's near.")
    time.sleep(a)
    print("I pack a back full of essentials and leave my room.")
    time.sleep(b)
    print("The transport bay is quieter than usual.")
    time.sleep(a)
    print("I find the correct shuttle and settle in my seat.")
    time.sleep(a)
    print("As we begin on our journey, I look out of the window towards the stars.")
    time.sleep(a)
    print("I wonder what I will find out there.")
    time.sleep(a)
    print("I doze in my seat.")
    time.sleep(b)
    print("Before long, an announcement plays.")
    time.sleep(a)
    print("We have arrived.")
    time.sleep(a)
    print("I am on an orbital platform high above moon WR34.")
    time.sleep(a)
    print("There are people moving around.")
    time.sleep(a)
    print("Maybe the miners who have been evacuated from the surface.")
    time.sleep(a)
    print("No one pays attention to me.")
    time.sleep(a)
    print("There is no need to.")
    time.sleep(a)
    print("I just follow the directions on my tablet.")
    time.sleep(a)
    print()
    m1 = ("Please proceed to shuttle 6 in bay 45.")
    for char in m1:
        sys.stdout.write(char)
        sys.stdout.flush()
        time.sleep(d)
    time.sleep(a)
    print()
    print()
    print("I make my way over there.")
    time.sleep(a)
    print("As I arrive, I find an empty shuttle 6 stands in front of me.")
    time.sleep(a)
    on_the_orbital_platform()


def on_the_orbital_platform():
    print()
    choice = input("Are you ready to depart?(y/n) ")
    if choice == "y":
        time.sleep(c)
        print()
        print("I sit down and fasten my seat belt.")
        time.sleep(a)
        print("The shuttle detects my presence and begins launch procedures.")
        time.sleep(a)
        print("We depart the orbital platform and glide down towards the moon base.")
        time.sleep(a)
        in_the_hanger()
    elif choice == "n":
        time.sleep(c)
        print()
        print("I should take a few moments to compose myself...")
        time.sleep(c)
        on_the_orbital_platform()
    else:
        time.sleep(c)
        print("Sorry, input not recognised")
        time.sleep(c)
        on_the_orbital_platform()

def in_the_hanger():
    print()
    print("=== Moon Base hanger === ")
    time.sleep(a)
    print("The hanger is large with a high ceiling.")
    time.sleep(a)
    print("The shuttle I used to get to the station stands in one corner.")
    time.sleep(a)
    print("There are moon rovers I can use to go out to the mining site.")
    time.sleep(a)
    print("There are also two doors. One leading to the command center. The other leading to the crew area.")
    time.sleep(a)
    print()
    print("Where should I go?")
    time.sleep(a)
    print("""1 - to the command center
2 - to the crew area
3 - take a buggy out to the mining site""")
    time.sleep(a)
    print()
    choice = input("choose a number and press enter: ")
    if choice == "1":
        time.sleep(c)
        in_the_command_center()
    elif choice == "2":
        time.sleep(c)
        in_the_crew_area()
    elif choice == "3":
        time.sleep(c)
        buggy_to_site()
    else:
        time.sleep(c)
        print("Sorry, input not recognised")
        time.sleep(c)
        in_the_hanger()

def in_the_command_center():
    print()
    print("=== Command center === ")
    time.sleep(a)
    print("The command center is deadly silent.")
    time.sleep(a)
    print("No one remains. They have all gone up to the orbital platform.")
    time.sleep(a)
    print("It's a spooky scene to see such a place completely empty.")
    time.sleep(a)
    print("I look around. Some of the computers are still turned on. ")
    time.sleep(a)
    print("Maybe I could access some information about what they found at the mining site.")
    time.sleep(a)
    print("There is also a door leading to the crew area, and a door leading to the hanger.")
    time.sleep(a)
    print()
    print("What should I do?")
    time.sleep(a)
    print("""1 - go to the crew area
2 - check the computer console
3 - go to the hanger""")
    print()
    time.sleep(a)
    choice = input("choose a number and press enter: ")
    if choice == "1":
        time.sleep(c)
        in_the_crew_area()
    elif choice == "2":
        time.sleep(c)
        check_computer()
    elif choice == "3":
        time.sleep(c)
        in_the_hanger()
    else:
        time.sleep(c)
        print("Sorry, input not recognised")
        time.sleep(c)
        in_the_command_center()

def check_computer():
    print()
    m1 = ("Loading...")
    for char in m1:
        sys.stdout.write(char)
        sys.stdout.flush()
        time.sleep(d)
    print()
    m2 = ("Report number: 483")
    for char in m2:
        sys.stdout.write(char)
        sys.stdout.flush()
        time.sleep(d)
    print()
    m3 = ("Author: Mining manager")
    for char in m3:
        sys.stdout.write(char)
        sys.stdout.flush()
        time.sleep(d)
    print()
    m4 = ("Our team have come across an item of interest.")
    for char in m4:
        sys.stdout.write(char)
        sys.stdout.flush()
        time.sleep(d)
    print()
    m5 = ("They have told me it is silver in color and buried underground.")
    for char in m5:
        sys.stdout.write(char)
        sys.stdout.flush()
        time.sleep(d)
    print()
    m6 = ("They uncovered it whilst mining.")
    for char in m6:
        sys.stdout.write(char)
        sys.stdout.flush()
        time.sleep(d)
    print()
    m7 = ("We are not sure how big it is as we have left it undisturbed.")
    for char in m7:
        sys.stdout.write(char)
        sys.stdout.flush()
        time.sleep(d)
    print()
    m8 = ("I have checked the records and I can't find any information about humans visiting this moon before us.")
    for char in m8:
        sys.stdout.write(char)
        sys.stdout.flush()
        time.sleep(d)
    print()
    m9 = ("It would therefore be quite possible that this object is of alien origin.")
    for char in m9:
        sys.stdout.write(char)
        sys.stdout.flush()
        time.sleep(d)
    print()
    m10 = ("Although it is also possible that someone may have come here in secret.")
    for char in m10:
        sys.stdout.write(char)
        sys.stdout.flush()
        time.sleep(d)
    print()
    m11 = ("I personally think that we should try and recover it ourself, but the rules don't allow for this.")
    for char in m11:
        sys.stdout.write(char)
        sys.stdout.flush()
        time.sleep(d)
    print()
    m12 = ("I have ordered an evacuation.")
    for char in m12:
        sys.stdout.write(char)
        sys.stdout.flush()
        time.sleep(d)
    print()
    m13 = ("We will return to the orbital platform and wait for further instructions.")
    for char in m13:
        sys.stdout.write(char)
        sys.stdout.flush()
        time.sleep(d)
    time.sleep(a)
    print()
    print()
    print("""1 - go to the crew area
2 - go to the hanger""")
    print()
    choice = input("choose a number and press enter: ")
    if choice == "1":
        time.sleep(c)
        in_the_crew_area()
    elif choice == "2":
        time.sleep(c)
        in_the_hanger()
    else:
        time.sleep(c)
        print("Sorry, input not recognised")
        time.sleep(c)
        check_computer()

def in_the_crew_area():
    print()
    print("=== Crew area === ")
    time.sleep(a)
    print("The crew obviously left in a rush.")
    time.sleep(a)
    print("There is half eaten food on tables, drinks, a pool table - abandoned mid game.")
    time.sleep(a)
    print("The television is still turned on in the corner of the room.")
    time.sleep(a)
    print("I see a tablet on one of the tables. It seems someone was writing a message at the time.")
    time.sleep(a)
    print()
    print("What should I do?")
    time.sleep(a)
    print("""1 - go to the hanger
2 - check the tablet
3 - go to the command center""")
    time.sleep(a)
    print()
    choice = input("choose a number and press enter: ")
    if choice == "1":
        time.sleep(c)
        in_the_hanger()
    elif choice == "2":
        time.sleep(c)
        check_tablet()
    elif choice == "3":
        time.sleep(c)
        in_the_command_center()
    else:
        time.sleep(c)
        print("Sorry, input not recognised")
        time.sleep(c)
        in_the_crew_area()

def check_tablet():
    print()
    m1 = ("Hi,")
    for char in m1:
        sys.stdout.write(char)
        sys.stdout.flush()
        time.sleep(d)
    print()
    m2 = ("Sorry I took so long to reply, I have been a little bit busy.")
    for char in m2:
        sys.stdout.write(char)
        sys.stdout.flush()
        time.sleep(d)
    print()
    m3 = ("I am working on a mining expedition right now and something big just happened.")
    for char in m3:
        sys.stdout.write(char)
        sys.stdout.flush()
        time.sleep(d)
    print()
    m4 = ("We came across something buried underground!")
    for char in m4:
        sys.stdout.write(char)
        sys.stdout.flush()
        time.sleep(d)
    print()
    m5 = ("It was made of metal.")
    for char in m5:
        sys.stdout.write(char)
        sys.stdout.flush()
        time.sleep(d)
    print()
    m6 = ("As soon as we found it our group leader got all agitated.")
    for char in m6:
        sys.stdout.write(char)
        sys.stdout.flush()
        time.sleep(d)
    print()
    m7 = ("He told us not to touch it and we all had to hurry back to the base.")
    for char in m7:
        sys.stdout.write(char)
        sys.stdout.flush()
        time.sleep(d)
    print()
    m8 = ("It's all a bit spooky if you ask me.")
    for char in m8:
        sys.stdout.write(char)
        sys.stdout.flush()
        time.sleep(d)
    print()
    m9 = ("What if we found an alien space ship or something?")
    for char in m9:
        sys.stdout.write(char)
        sys.stdout.flush()
        time.sleep(d)
    print()
    m10 = ("Oh wait, even more crazy, we just got told to evacuate.")
    for char in m10:
        sys.stdout.write(char)
        sys.stdout.flush()
        time.sleep(d)
    print()
    m11 = ("I can't believe it.")
    for char in m11:
        sys.stdout.write(char)
        sys.stdout.flush()
        time.sleep(d)
    print()
    m12 = ("This kind of this has never happened before.")
    for char in m12:
        sys.stdout.write(char)
        sys.stdout.flush()
        time.sleep(d)
    print()
    m13 = ("Do you think it is dangerous?.")
    for char in m13:
        sys.stdout.write(char)
        sys.stdout.flush()
        time.sleep(d)
    print()
    m14 = ("I'm a little bit worried to be honest.")
    for char in m14:
        sys.stdout.write(char)
        sys.stdout.flush()
        time.sleep(d)
    print()
    m15 = ("Any way, I have to go.")
    for char in m15:
        sys.stdout.write(char)
        sys.stdout.flush()
        time.sleep(d)
    print()
    m16 = ("Speak to you again. (I hope!)")
    for char in m16:
        sys.stdout.write(char)
        sys.stdout.flush()
        time.sleep(d)
    print()
    m17 = ("From Marco")
    for char in m17:
        sys.stdout.write(char)
        sys.stdout.flush()
        time.sleep(d)
    print()
    print()
    time.sleep(a)
    print("""1 - go to the command center
2 - go to the hanger""")
    print()
    choice = input("choose a number and press enter: ")
    if choice == "1":
        time.sleep(c)
        in_the_command_center()
    elif choice == "2":
        time.sleep(c)
        in_the_hanger()
    else:
        time.sleep(c)
        print("Sorry, input not recognised")
        time.sleep(c)
        check_tablet()

def buggy_to_site():
    print()
    print("I power up the buggy and drive out of the hanger.")
    time.sleep(a)
    print("The moon's surface stretches out in front of me.")
    time.sleep(a)
    print("A beautiful site.")
    time.sleep(a)
    print("I drive the buggy in the direction of the mining site.")
    time.sleep(a)
    print("Checking the map as I go.")
    time.sleep(a)
    print("I near the site.")
    time.sleep(a)
    print("There is a small hill to my left, it would offer an excellent view over the site.")
    time.sleep(a)
    print("Straight ahead lies the mining site.")
    time.sleep(a)
    print()
    print("Should I go up the hill? Or just carry on?")
    time.sleep(a)
    print("""1 - go up the hill
2 - go straight to the site""")
    time.sleep(a)
    print()
    choice = input("choose a number and press enter: ")
    if choice == "1":
        time.sleep(c)
        high_ground()
    elif choice == "2":
        time.sleep(c)
        approaching_object()
    else:
        time.sleep(c)
        print("Sorry, input not recognised")
        time.sleep(c)
        buggy_to_site()

def high_ground():
    print()
    print("The buggy slowly makes its way up the hill.")
    time.sleep(a)
    print("Nearer and nearer to the summit.")
    time.sleep(a)
    print("As I arrive I look down onto the mining site.")
    time.sleep(a)
    print("I can see mining equipment lying around on the floor.")
    time.sleep(a)
    print("The bright colors contrasting against the dull surface of the moon.")
    time.sleep(a)
    print("Then, in the centre I spot a small silver object peeping out of the ground.")
    time.sleep(a)
    print("It must be the object.")
    time.sleep(a)
    print()
    print("1 - go down to the object")
    time.sleep(a)
    print()
    choice = input("choose a number and press enter: ")
    if choice == "1":
        time.sleep(c)
        approaching_object()
    else:
        time.sleep(c)
        print("Sorry, input not recognised")
        time.sleep(c)
        high_ground()

def approaching_object():
    print()
    print("I cautiously move closer to the object.")
    time.sleep(a)
    print("Calm and excited at the same time.")
    time.sleep(a)
    print("Something crosses my mind.")
    time.sleep(a)
    print("My rifle.")
    time.sleep(a)
    print("What if I need it? What if the machine is dangerous?")
    time.sleep(a)
    print("Should I get it ready? just in case?")
    time.sleep(a)
    print()
    print("""1 - prepare rifle
2 - don't prepare rifle.""")
    time.sleep(a)
    print()
    choice = input("choose a number and press enter: ")
    if choice == "1":
        time.sleep(c)
        approach_with_rifle()
    elif choice == "2":
        time.sleep(c)
        approach_without_rifle()
    else:
        time.sleep(c)
        print("Sorry, input not recognised")
        time.sleep(c)
        approaching_object()

def approach_with_rifle():
    print()
    print("I approach the object slowly with my rifle ready.")
    time.sleep(a)
    print("As I approach the object seems to make a noise.")
    time.sleep(a)
    print("What appears to be a small sensor rises up.")
    time.sleep(a)
    print("Looking at me.")
    time.sleep(a)
    print("In an instant a second item rises up.")
    time.sleep(a)
    print("It clearly has the appearance of a gun...")
    time.sleep(a)
    print("I immediately turn away and the gun starts shooting.")
    time.sleep(a)
    print("The projectiles fly over my head, narrowly missing me.")
    time.sleep(a)
    print("I dive behind some mining equipment to take cover.")
    time.sleep(a)
    print("I can't believe it.")
    time.sleep(a)
    print()
    print("What should I do now?")
    time.sleep(a)
    print("""1 - return fire
2 - escape back up the hill to higher ground""")
    time.sleep(a)
    print()
    choice = input("choose a number and press enter: ")
    if choice == "1":
        time.sleep(c)
        return_fire()
    elif choice == "2":
        time.sleep(c)
        escape_high_ground()
    else:
        time.sleep(c)
        print("Sorry, input not recognised")
        time.sleep(c)
        approach_with_rifle()

def return_fire():
    print()
    print("I brace myself.")
    time.sleep(a)
    print("Taking a deep breath.")
    time.sleep(a)
    print("I peek out from behind the equipment to see the object.")
    time.sleep(a)
    print("It just sits there motionless.")
    time.sleep(a)
    print("I rise up further aiming the rifle towards the object.")
    time.sleep(a)
    print("Firing three shots.")
    time.sleep(a)
    print("One misses.")
    time.sleep(a)
    print("Two hit.")
    time.sleep(a)
    print("Both shots brush across the shell of the object and fly into the distance.")
    time.sleep(a)
    print("It seems it took no damage.")
    time.sleep(a)
    print("Then suddenly, the object returns fire.")
    time.sleep(a)
    print("One shot misses.")
    time.sleep(a)
    print("But the other hits.")
    time.sleep(a)
    print("I am thrown to the floor where I lie for several moments.")
    time.sleep(a)
    print("I try to move but it seems the body suit is damaged.")
    time.sleep(a)
    print("I can't move.")
    time.sleep(a)
    print("What do I do now?")
    time.sleep(a)
    print()
    print("1 - call for help")
    time.sleep(a)
    print()
    choice = input("choose a number and press enter: ")
    if choice == "1":
        time.sleep(c)
        print()
        print("I reach over to the input panel and press \"Emergency\".")
        time.sleep(a)
        print("a message appears")
        time.sleep(a)
        print()
        m1 = ("...dispatching autonomous recovery rover...")
        for char in m1:
            sys.stdout.write(char)
            sys.stdout.flush()
            time.sleep(d)
        time.sleep(a)
        print()
        print()
        print("I lie there completely still.")
        time.sleep(b)
        print("Before long, I hear the noise of the rover.")
        time.sleep(a)
        print("I'm safe.")
        time.sleep(a)
        damaged_in_hanger()
    else:
        time.sleep(c)
        print("Sorry, input not recognised")
        time.sleep(c)
        return_fire()

def escape_high_ground():
    print()
    print("I brace myself.")
    time.sleep(a)
    print("Taking a deep breath.")
    time.sleep(a)
    print("I peek out from behind the equipment to see the object.")
    time.sleep(a)
    print("It just sits there motionless.")
    time.sleep(a)
    print("I turn back and look the other way.")
    time.sleep(a)
    print("I can see the hill in front of me.")
    time.sleep(a)
    print("I break from cover and race towards the hill.")
    time.sleep(a)
    print("I scramble up to the top as fast as I can before peering back over the ledge to see the object.")
    time.sleep(a)
    print("I'm quite far away now.")
    time.sleep(a)
    print("But I can't run any further. I have to deal with this now.")
    time.sleep(a)
    print("Should I shoot from here? ")
    time.sleep(a)
    print("Or should I call in a missile strike from the orbital platform?")
    time.sleep(a)
    print("It would surely destroy the object, but what good is it destroyed?.")
    time.sleep(a)
    print()
    print("""1 - shoot at the object
2 - call in missile strike from the orbital platform""")
    time.sleep(a)
    print()
    choice = input("choose a number and press enter: ")
    if choice == "1":
        time.sleep(c)
        shoot_from_high()
    elif choice == "2":
        time.sleep(c)
        call_in_strike()
    else:
        time.sleep(c)
        print("Sorry, input not recognised")
        time.sleep(c)
        escape_high_ground()

def shoot_from_high():
    print()
    print("I brace myself.")
    time.sleep(a)
    print("Taking a deep breath.")
    time.sleep(a)
    print("I peek out from behind the ledge to see the object.")
    time.sleep(a)
    print("It just sits there motionless.")
    time.sleep(a)
    print("I rise up further aiming the rifle towards the object.")
    time.sleep(a)
    print("Firing three shots.")
    time.sleep(a)
    print("One misses.")
    time.sleep(a)
    print("Two hit.")
    time.sleep(a)
    print("Both shots brush across the shell of the object and fly into the distance.")
    time.sleep(a)
    print("It seems it took no damage.")
    time.sleep(a)
    print("Then suddenly, the object returns fire.")
    time.sleep(a)
    print("One shot misses.")
    time.sleep(a)
    print("But the other hits.")
    time.sleep(a)
    print("I am thrown to the floor where I lie for several moments.")
    time.sleep(a)
    print("I try to move but it seems the body suit is damaged.")
    time.sleep(a)
    print("I can't move.")
    time.sleep(a)
    print()
    print("What do I do now?")
    time.sleep(a)
    print("1 - call for help")
    time.sleep(a)
    print()
    choice = input("choose a number and press enter: ")
    if choice == "1":
        time.sleep(c)
        print()
        print("I reach over to the input panel and press \"Emergency\".")
        time.sleep(a)
        print("a message appears")
        time.sleep(a)
        print()
        m1 = ("...dispatching autonomous recovery rover...")
        for char in m1:
            sys.stdout.write(char)
            sys.stdout.flush()
            time.sleep(d)
        time.sleep(a)
        print()
        print()
        print("I lie there completely still.")
        time.sleep(b)
        print("Before long, I hear the noise of the rover.")
        time.sleep(a)
        print("I'm safe.")
        time.sleep(a)
        damaged_in_hanger()
    else:
        time.sleep(c)
        print("Sorry, input not recognised")
        time.sleep(c)
        shoot_from_high()

def call_in_strike():
    print()
    print("I set the rifle to targeting mode and slowly point it at the object.")
    time.sleep(a)
    print("looking through the scope I can see the laser marker on the object.")
    time.sleep(a)
    print("I gently pull the trigger then turn and move away from the ledge.")
    time.sleep(a)
    print("Was this the right thing to do?")
    time.sleep(a)
    print("I wait.")
    time.sleep(b)
    print("...and wait...")
    time.sleep(b)
    print("Without forewarning, there is a huge flash of light.")
    time.sleep(a)
    print("The missile hit its target.")
    time.sleep(a)
    print("I stand up and slowly walk down towards were the object was, rifle ready.")
    time.sleep(a)
    print("There is little left.")
    time.sleep(a)
    print("The mining equipment is destroyed and so it seems was the object.")
    time.sleep(a)
    print("Smashed to pieces.")
    time.sleep(a)
    print("=== The end ===")
    sys.exit()



def approach_without_rifle():
    print()
    print("I approach the object slowly.")
    time.sleep(a)
    print("When I reach the site I stand over the object to look at it.")
    time.sleep(a)
    print("A slightly curved and silver machine coming out of the ground.")
    time.sleep(a)
    print("It seems to be completely lifeless.")
    time.sleep(a)
    print("I pause for a moment.")
    time.sleep(a)
    print("What is this?")
    time.sleep(a)
    print("What's inside of it?")
    time.sleep(a)
    print("I take out my cutting equipment.")
    time.sleep(a)
    print()
    print("""1 - cut open the machine""")
    time.sleep(a)
    print()
    choice = input("choose a number and press enter: ")
    if choice == "1":
        time.sleep(c)
        cut_open_machine()
    else:
        time.sleep(c)
        print("Sorry, input not recognised")
        time.sleep(c)
        approach_without_rifle()

def cut_open_machine():
    print()
    print("I crouch down and bring the cutting tool close to the object.")
    time.sleep(a)
    print("As I power up the equipment the object seems to make a noise.")
    time.sleep(a)
    print("What appears to be a small sensor rises up.")
    time.sleep(a)
    print("Looking at me.")
    time.sleep(a)
    print("In an instant a second item rises up.")
    time.sleep(a)
    print("It clearly has the appearance of a gun...")
    time.sleep(a)
    print("I immediately turn away and the gun starts shooting.")
    time.sleep(a)
    print("The projectiles fly over my head, narrowly missing me.")
    time.sleep(a)
    print("I dive behind some mining equipment to take cover.")
    time.sleep(a)
    print("I wait for a moment.")
    time.sleep(a)
    print("I can't believe it.")
    time.sleep(a)
    print("I take my rifle and ready it for action.")
    time.sleep(a)
    print()
    print("What should I do now?")
    time.sleep(a)
    print("""1 - return fire
    2 - escape back up the hill to higher ground""")
    time.sleep(a)
    print()
    choice = input("choose a number and press enter: ")
    if choice == "1":
        time.sleep(c)
        return_fire()
    elif choice == "2":
        time.sleep(c)
        escape_high_ground()
    else:
        time.sleep(c)
        print("Sorry, input not recognised")
        time.sleep(c)
        cut_open_machine()

def damaged_in_hanger():
    print()
    print("The recovery rover drags me back to the moon base and into the hanger.")
    time.sleep(a)
    print("Once inside I escape from the body suit and look at the damage.")
    time.sleep(a)
    print("I'm lucky to be alive.")
    time.sleep(a)
    print("The object is dangerous.")
    time.sleep(a)
    print("It needs to be destroyed.")
    time.sleep(a)
    print("I have no choice.")
    time.sleep(a)
    print("I have to go back there and call in a missile strike.")
    time.sleep(a)
    print()
    print("1 - go back to high ground above site")
    time.sleep(a)
    print()
    choice = input("choose a number and press enter: ")
    if choice == "1":
        time.sleep(c)
        return_to_high_ground()
    else:
        time.sleep(c)
        print("Sorry, input not recognised")
        time.sleep(c)
        damaged_in_hanger()

def return_to_high_ground():
    print()
    print("I make my way back across the moon's surface to the site.")
    time.sleep(a)
    print("When I arrive I creep up the hill overlooking the site until I can see the object.")
    time.sleep(a)
    print("There is only one thing left to do.")
    time.sleep(a)
    print()
    print("1 - call in missile strike")
    time.sleep(a)
    print()
    choice = input("choose a number and press enter: ")
    if choice == "1":
        time.sleep(c)
        call_in_strike()
    else:
        time.sleep(c)
        print("Sorry, input not recognised")
        time.sleep(c)
        return_to_high_ground()

# starting script

def readmessage():
    print()
    mess_yn = input("Do you want to read the message? (type y and press enter) ")
    if mess_yn == "y":
        time.sleep(c)
        print()
        m1 = ("###MESSAGE###")
        for char in m1:
            sys.stdout.write(char)
            sys.stdout.flush()
            time.sleep(d)
        print()
        m2 = ("Miners working on moon WR34 have discovered an object during their work.")
        for char in m2:
            sys.stdout.write(char)
            sys.stdout.flush()
            time.sleep(d)
        print()
        m3 = ("We are currently unsure as to what this object is.")
        for char in m3:
            sys.stdout.write(char)
            sys.stdout.flush()
            time.sleep(d)
        print()
        m4 = ("As a precaution we have evacuated all miners to the orbital platform.")
        for char in m4:
            sys.stdout.write(char)
            sys.stdout.flush()
            time.sleep(d)
        print()
        m5 = ("We are hoping that you will go and investigate this discovery.")
        for char in m5:
            sys.stdout.write(char)
            sys.stdout.flush()
            time.sleep(d)
        print()
        time.sleep(c)
        accept_func()
    else:
        time.sleep(c)
        readmessage()

# Start

print("I awake gently in my sleeping room...")
time.sleep(a)
print("...opening my eyes slightly to look around.")
time.sleep(a)
print("The room is dark, only slightly illuminated by a blue night light.")
time.sleep(a)
print("The communication device is making a noise and vibrating slightly.")
time.sleep(a)
print("I look over at the screen...")
time.sleep(a)
print()

message = ("...incoming message...")
for char in message:
    sys.stdout.write(char)
    sys.stdout.flush()
    time.sleep(d)
time.sleep(a)
print()

readmessage()


